name: Update AzuraCast iCal

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Removed the docs folder creation step to keep the workspace clean

    - name: Run schedule exporter
      run: python export_schedule.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        # Changed this line to add the file from the root folder instead of /docs
        git add azuracast_schedule.ics
        git diff-index --quiet HEAD || git commit -m "Automated calendar update for all stations"
        git push
